site_name: MCP for WooCommerce
site_description: WooCommerce MCP Server — WordPress MCP plugin implementing the Model Context Protocol (MCP)
repo_url: https://github.com/iOSDevSK/mcp-for-woocommerce
site_url: https://iosdevsk.github.io/mcp-for-woocommerce/
edit_uri: edit/main/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
  custom_dir: docs/overrides
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - tables
  - attr_list
  - footnotes
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iOSDevSK/mcp-for-woocommerce
    - icon: fontawesome/solid/globe
      link: https://iosdevsk.github.io/mcp-for-woocommerce/
nav:
  - Overview: index.md
  - Announcement: announcement.md
  - Use Cases: use-cases.md
  - LLM Integration: integration.md
  - WooCommerce MCP:
    - What is WooCommerce MCP Server?: woocommerce-mcp-server/what-is.md
    - Install: woocommerce-mcp-server/install.md
    - Configure: woocommerce-mcp-server/configure.md
    - Examples: woocommerce-mcp-server/examples.md
    - Troubleshooting: woocommerce-mcp-server/troubleshooting.md
    - FAQ: woocommerce-mcp-server/faq.md
