site_name: Woo MCP
site_description: WooCommerce MCP Server — WordPress MCP plugin implementing the Model Context Protocol (MCP)
repo_url: https://github.com/iOSDevSK/woo-mcp
site_url: https://iosdevsk.github.io/woo-mcp/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - tables
  - attr_list
  - footnotes
plugins:
  - search
  - sitemap:
      changefreq: weekly
      priority: 0.6
nav:
  - Overview: index.md
  - WooCommerce MCP:
    - What is WooCommerce MCP Server?: woocommerce-mcp-server/what-is.md
    - Install: woocommerce-mcp-server/install.md
    - Configure: woocommerce-mcp-server/configure.md
    - Examples: woocommerce-mcp-server/examples.md
    - Troubleshooting: woocommerce-mcp-server/troubleshooting.md
    - FAQ: woocommerce-mcp-server/faq.md
