name: Deploy WordPress Plugin

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to the specific plugin directory
          cd /var/www/html/wp-content/plugins/
          
          # Remove existing directory if it exists
          if [ -d "woo-mcp" ]; then
            echo "Backing up existing plugin..."
            mv woo-mcp woo-mcp-backup-$(date +%Y%m%d-%H%M%S) 2>/dev/null || true
          fi
          
          # Fresh clone of the repository
          echo "Cloning fresh copy from repository..."
          git clone https://github.com/iOSDevSK/woo-mcp.git woo-mcp
          cd woo-mcp
          
          # Verify we have the latest commit
          echo "Current commit:"
          git log --oneline -1
          
          # Check if the correct branding is in place
          echo "Checking plugin branding:"
          grep "Plugin name:" wordpress-mcp.php
          
          # Force deployment timestamp
          echo "Deployment completed at: $(date)"
          echo "Latest commit deployed: $(git log --oneline -1)"
          
          # Re-enable the plugin (fixes have been applied)
          if [ -d "/var/www/html/wp-content/plugins/woo-mcp-emergency-disabled" ]; then
            mv /var/www/html/wp-content/plugins/woo-mcp-emergency-disabled /var/www/html/wp-content/plugins/woo-mcp 2>/dev/null || true
            echo "Plugin re-enabled after emergency fixes"
          fi
          
          # Set proper permissions
          chown -R www-data:www-data /var/www/html/wp-content/plugins/woo-mcp/
          chmod -R 755 /var/www/html/wp-content/plugins/woo-mcp/
          
          # Verify deployment
          echo "Checking deployed files:"
          ls -la /var/www/html/wp-content/plugins/woo-mcp/
          echo "Checking for changelog.txt:"
          ls -la /var/www/html/wp-content/plugins/woo-mcp/changelog.txt || echo "changelog.txt not found"
          
          # Clear PHP OPcache to ensure changes take effect
          if command -v php >/dev/null 2>&1; then
            php -r "if (function_exists('opcache_reset')) opcache_reset();"
          fi
          
          # Clear any WordPress caches
          if command -v wp >/dev/null 2>&1; then
            wp cache flush --allow-root 2>/dev/null || true
          fi
          
          echo "Deployment completed successfully"
