name: Deploy WordPress Plugin

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/wp-content/plugins/woo-mcp
          
          # Stash any local changes to avoid conflicts
          git stash push -m "Auto-stash before deployment" || true
          
          # Pull latest changes
          git pull origin main
          
          # Clear PHP OPcache to ensure updated code is loaded
          if command -v php >/dev/null 2>&1; then
            php -r "if (function_exists('opcache_reset')) opcache_reset();"
          fi
          
          # Clear WordPress cache and force plugin reload
          cd /var/www/html
          wp cache flush 2>/dev/null || true
          wp plugin deactivate woo-mcp 2>/dev/null || true
          wp plugin activate woo-mcp 2>/dev/null || true
          
          echo "Deployment completed successfully"
