name: Deploy WordPress Plugin

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/wp-content/plugins/
          
          # Stash any local changes
          git stash 2>/dev/null || true
          
          # Update the plugin
          git pull origin main
          
          # Re-enable the plugin (fixes have been applied)
          if [ -d "woo-mcp-emergency-disabled" ]; then
            mv woo-mcp-emergency-disabled woo-mcp 2>/dev/null || true
            echo "Plugin re-enabled after emergency fixes"
          fi
          
          # Clear PHP OPcache to ensure changes take effect
          if command -v php >/dev/null 2>&1; then
            php -r "if (function_exists('opcache_reset')) opcache_reset();"
          fi
          
          # Clear any WordPress caches
          if command -v wp >/dev/null 2>&1; then
            wp cache flush --allow-root 2>/dev/null || true
          fi
          
          echo "Deployment completed successfully"
