name: Deploy WordPress Plugin

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e  # Exit on any error
          
          PLUGIN_DIR="/var/www/html/wp-content/plugins/woo-mcp"
          REPO_URL="https://github.com/${{ github.repository }}.git"
          
          echo "Starting deployment of commit ${{ github.sha }}"
          
          # Navigate to plugins directory
          cd /var/www/html/wp-content/plugins/
          
          # Backup existing plugin if it exists
          if [ -d "woo-mcp" ]; then
            echo "Creating backup of existing plugin..."
            BACKUP_NAME="woo-mcp-backup-$(date +%Y%m%d-%H%M%S)"
            if ! mv woo-mcp "$BACKUP_NAME"; then
              echo "Failed to create backup, aborting deployment"
              exit 1
            fi
            echo "Backup created: $BACKUP_NAME"
          fi
          
          # Clone repository
          echo "Cloning repository from $REPO_URL..."
          if ! git clone "$REPO_URL" woo-mcp; then
            echo "Failed to clone repository"
            # Restore backup if clone fails
            if [ -d "$BACKUP_NAME" ]; then
              mv "$BACKUP_NAME" woo-mcp
              echo "Restored backup due to clone failure"
            fi
            exit 1
          fi
          
          cd woo-mcp
          
          # Verify we're on the correct commit
          DEPLOYED_COMMIT=$(git rev-parse HEAD)
          echo "Deployed commit: $DEPLOYED_COMMIT"
          echo "Expected commit: ${{ github.sha }}"
          
          if [ "$DEPLOYED_COMMIT" != "${{ github.sha }}" ]; then
            echo "Warning: Deployed commit doesn't match expected commit"
          fi
          
          # Verify plugin file exists
          if [ ! -f "wordpress-mcp.php" ]; then
            echo "Error: Main plugin file not found"
            exit 1
          fi
          
          # Set proper permissions
          echo "Setting file permissions..."
          chown -R www-data:www-data "$PLUGIN_DIR"
          chmod -R 755 "$PLUGIN_DIR"
          
          # Clear caches
          echo "Clearing caches..."
          if command -v php >/dev/null 2>&1; then
            php -r "if (function_exists('opcache_reset')) { opcache_reset(); echo 'OPcache cleared\n'; }"
          fi
          
          if command -v wp >/dev/null 2>&1; then
            wp cache flush --allow-root 2>/dev/null && echo "WordPress cache cleared" || echo "WordPress cache clear failed (non-critical)"
          fi
          
          # Install dependencies and build
          echo "Installing dependencies..."
          
          # Install Composer dependencies
          if [ -f "composer.json" ]; then
            echo "Running composer install..."
            if command -v composer >/dev/null 2>&1; then
              composer install --no-dev --optimize-autoloader || echo "Composer install failed"
            else
              echo "Composer not found, skipping composer install"
            fi
          else
            echo "No composer.json found, skipping composer install"
          fi
          
          # Install npm dependencies
          if [ -f "package.json" ]; then
            echo "Running npm install..."
            if command -v npm >/dev/null 2>&1; then
              npm install --production || echo "npm install failed"
            else
              echo "npm not found, skipping npm install"
            fi
          else
            echo "No package.json found, skipping npm install"
          fi
          
          # Build assets
          if [ -f "package.json" ] && command -v npm >/dev/null 2>&1; then
            echo "Running npm run build..."
            npm run build || echo "npm run build failed"
          else
            echo "Skipping npm run build (no package.json or npm not available)"
          fi
          
          # Verify deployment
          echo "Verifying deployment..."
          ls -la "$PLUGIN_DIR/wordpress-mcp.php" || echo "Main plugin file check failed"
          
          echo "Deployment completed successfully at $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
