name: Deploy WordPress Plugin

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/wp-content/plugins/
          
          # EMERGENCY: Permanently disable plugin until manual recovery
          if [ -d "woo-mcp" ]; then
            mv woo-mcp woo-mcp-emergency-disabled 2>/dev/null || true
            echo "Plugin emergency disabled due to 500 errors"
          fi
          
          # Clear PHP OPcache to ensure changes take effect
          if command -v php >/dev/null 2>&1; then
            php -r "if (function_exists('opcache_reset')) opcache_reset();"
          fi
          
          # Clear any WordPress caches
          if command -v wp >/dev/null 2>&1; then
            wp cache flush --allow-root 2>/dev/null || true
          fi
          
          echo "Deployment completed successfully"
