name: Deploy WordPress Plugin

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        
    - name: Install dependencies and build
      run: |
        npm install
        composer install --no-dev --optimize-autoloader
        npm run build
        
    - name: Upload built plugin
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: |
          .
          !.git
          !node_modules
          !tests
          !.github
          !src
          !*.md
          !package*.json
          !composer.json
          !composer.lock
          !phpunit.xml
          !.gitignore
        target: /var/www/html/wp-content/plugins/woo-mcp-new/
        
    - name: Activate deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Re-enable the plugin (fixes have been applied)
          if [ -d "/var/www/html/wp-content/plugins/woo-mcp-emergency-disabled" ]; then
            rm -rf /var/www/html/wp-content/plugins/woo-mcp-emergency-disabled
            echo "Removed emergency disabled plugin"
          fi
          
          # Backup current version if exists
          if [ -d "/var/www/html/wp-content/plugins/woo-mcp" ]; then
            mv /var/www/html/wp-content/plugins/woo-mcp /var/www/html/wp-content/plugins/woo-mcp-backup-$(date +%Y%m%d-%H%M%S)
            echo "Backed up previous version"
          fi
          
          # Atomic swap to new version
          mv /var/www/html/wp-content/plugins/woo-mcp-new /var/www/html/wp-content/plugins/woo-mcp
          echo "Deployed new version"
          
          # Set proper permissions
          chown -R www-data:www-data /var/www/html/wp-content/plugins/woo-mcp
          chmod -R 755 /var/www/html/wp-content/plugins/woo-mcp
          
          # Clear PHP OPcache to ensure changes take effect
          if command -v php >/dev/null 2>&1; then
            php -r "if (function_exists('opcache_reset')) opcache_reset();"
          fi
          
          # Clear any WordPress caches
          if command -v wp >/dev/null 2>&1; then
            wp cache flush --allow-root 2>/dev/null || true
          fi
          
          echo "Deployment completed successfully"
